{% set name = "pyhunspell" %}
{% set version = "0.5.3" %}
{% set sha256 = "27c69998268314decfa3fea5e585ab09e532d1f2105ad2701f604493a6c8e832" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/blatinier/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - toolchain
  run:
    - python
    - hunspell

test:
  imports:
    - hunspell

about:
  home: http://github.com/blatinier/pyhunspell
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: 'Python binding for hunspell'

  description: |
    Python binding for Hunspell usage.
  doc_url: https://github.com/blatinier/pyhunspell/wiki/Documentation
  dev_url: https://github.com/blatinier/pyhunspell

extra:
  recipe-maintainers:
    - blatinier
